# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d54dfc7b91716ab4f1adb8f70a9167256c4c66ab5d029918f2e1016b8d7b691d8afe3c5cb838b01f2dba2dc40568e256dd7b991d0f4653a8385a5753c3e487

test:
  secret_key_base: dfa8be180d8345b23d0a194805bd6e511d6764a203b070c7c11e609579a0e91b4044af6531f6ec809aba6ba69a6ab57882794044fb1b95ce2e5a9d8eb72c9291

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
